### ISSUE TITLE
Crashes when executing the nnp_softmax_output function

### ISSUE THREAD

**Issue by liuyi999111** [Maratyszcza/NNPACK#63]
Call functions in file softmax-output.c:
![bp1](https://cloud.githubusercontent.com/assets/13236407/24184653/0acc2566-0f0a-11e7-9e14-881ce0ab1a5f.jpeg)
Crashes in file pthreadpool.c line 291:
SIGSEGV (signal SIGSEGV: invalid address (fault address: 0x0)).
Is the outplace_softmax_context structure not properly initialized?

**Comment by Maratyszcza** [comment]
Probably you are build NNPACK for a new architecture? See https://github.com/Maratyszcza/NNPACK/blob/master/src/softmax-output.c#L67

**Comment by liuyi999111** [comment]
I use the script provided by the NNPACK to build the static library.
${NNPACK}/obj/local/arm64-v8a/libnnpack.a
Do I need to specify a architecture? I want to use NNPACK in Android OS.

**Comment by Maratyszcza** [comment]
Indeed, there was a bug. Should be fixed now in 91c3d15fdec4176f54ab487fc0ed9433521a792b

**Comment by liuyi999111** [comment]
@Maratyszcza But this bug is not really fixed.
nnp_hwinfo.activations.outplace_softmax and nnp_hwinfo.activations.inplace_softmax is not properly initialized.

**Comment by Maratyszcza** [comment]
Make sure you pull the repo and rebuild everything

**Comment by liuyi999111** [comment]
It works. Thank you.
